version: "2.26.1-desktop.1"
services:
  jobportal-app:
    build: .
    ports:
      -   "8080:8080"
    networks:
      - job-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pandey
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: JobPortal
    ports:
      - 5432:5432
    networks:
      - job-network
    volumes:
      - job-pg-data:/var/lib/postgresql/data

networks:
  job-network:
    driver: bridge

volumes:
  job-pg-data:
