spring:
  application:
    name: JobPortal

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  datasource:
    url: jdbc:postgresql://postgres:5432/JobPortal
    username: pandey
    password: 1234
    driver-class-name: org.postgresql.Driver

server:
  port: 8080