spring:
  application:
    name: JobPortal

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/JobPortal
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
